### ISSUE TITLE
To this day I still have not received any confirmation on the wallet.

### ISSUE THREAD

**Issue by johntoi** [hexxcointakeover/hexxcoin#19]
When I installed 3 files:
hexxcoin-cli
hexxcoind
The avast software reports a file containing malicious information.
When booting hexxcoin-qt it displays the bottom corner:
no block source available ........ 1 year (s) and 27 week (s) behind.

I have a transfer order hxx check in block:
Details for Address
Address HELptHjeSeaNDBuztUq6MPxJCxEZajARARat
Balance 36.57242089 HXX
Rich List Rank 1218 với khối 327531 với 36.57242089 HXX
Guesstimated Wallet none
Received 36.57242089 HXX in 1 transactions
Sent 0.0 HXX in 0 transactions

Transactions
Hash Block Amount / Amount
80954f36d145b189 ... 325606 2018-08-29 14:13:52 + 36.57242089 HXX 36.57242089 HXX

To this day I still have not received any confirmation on the wallet.
Should I remove and reload my wallet?
I use win 10.
Information wallet.
v4.0.4.2-0adefaa-travis
/Hexx4.0.4.2/
Berkeley DB 4.8.30: (April 9, 2010
Sun Sep 2 10:33:43 2018
main
16 (In: 0 / Out: 16) 16 (In: 0 / Out: 16)
current number of blocks: 10119
...
I'm afraid of losing my coin. Please help me solve the problem with my thanks.

**Comment by devcon-gh** [comment]
Install the chainfiles

Stop/quit your running wallet
Navigate to your hexxcoin application folder
(Windows) -> C:\Users\Username\AppData\Roaming\hexxcoin
(Mac) -> /Users/Username/Library/Application Support/hexxcoin
(Unix) -> /.hexxcoin
Always backup your wallet.dat file from the application folder
Remove/delete all folders and files from the application folder EXCEPT wallet.dat (and xnode.conf if you run an Xnode)
Download the latest chainfiles -> https://github.com/hexxcointakeover/hexxcoin/releases/download/chain/chainfiles.zip
Extract/unzip the chainfiles.zip file and copy/paste chainstate, blocks and db.log in the application folder:
Restart your wallet

**Comment by johntoi** [comment]
Thank you. I have done the tutorial and have synced the data.
But still have not received hexx coin.
I checked the block "Not yet redeemed"

"
Details for Transaction
Hash 80954f36d145b1899cbe942cc90f28119e3801f3f23585dc2897c6001abeff1d
Block Height 325606: 1 (2828 confirmations)
Block Date / Time 2018-08-29 14:13:52
Total Output 59.02846454 HXX Giá trị 0.000373 HXX
Inputs / Outputs
Raw Transaction
Inputs
Index Previous output Address Amount
0 in 325583 HPfNjAYaVraFwDGsr6Z758AZ5Tiq4eT3FA 26.78748566 HXX
1 in 32fps:
Outputs
Index Redeemed in Address Amount
0 Not yet redeemed HELPTHeSeaNDBuztUq6MPxJCxEZajARat 36.57242089 HXX
.

What should I do? Please can help!
