### ISSUE TITLE
Wallet will not finish updating

### ISSUE THREAD

**Issue by revizionary1** [hexxcointakeover/hexxcoin#3]
It is stuck at 25 percent after it became current. Now all it says is "synchronizing additional data at 25 percent." There is a warning on my Windows 64 bit version that says "Warning unknown rules activated" (versionbit 0). This is the newest version of your Hexxcoin Core wallet.

What is going on. The link provided was : https://github.com/hexxcointakeover/4.0.1.X/releases/tag/4.0.2.2

That is where this wallet was downloaded from. Why the 3 day standstill at 25 percent additional data? You have a glitch.

**Comment by revizionary1** [comment]
I also downloaded a second wallet and placed it on my laptop. SAME ISSUE at additional data 25 percent.

**Comment by hexxcointakeover** [comment]
fixed

**Comment by revizionary1** [comment]
Thanks. I already put my coins in from Cryptopia...and it was fast.
