### ISSUE TITLE
unlock wallet button

### ISSUE THREAD

**Issue by zapiq** [hexxcointakeover/hexxcoin#4]
There is no unlock wallet option in the qt menu  v4.0.2.3

**Comment by devcon-gh** [comment]
True, but you can unlock and lock your wallet also in the debug console of the qt. For example, if you want to unlock the wallet for like 60 seconds you can use the command: `walletpassphrase "your pass phrase" 60`. If you want to lock the wallet again use the command: `walletlock`.

**Comment by manuelasayago** [comment]
I do not know how to install the wallet on a Mac. I think it would be good to publish some instructions for people who do not know much about programming.

**Comment by manuelasayago** [comment]
Maybe I have to use the terminal?

**Comment by devcon-gh** [comment]
I like to invite you to our Discord channel, we have a hexx-wallet-help section. I can guide you there to setup your wallet on a Mac. https://discord.gg/fADCkKC

**Comment by manuelasayago** [comment]
Thanks!

**Comment by Kourdoulos** [comment]
hi devcon-gh, fo you know about the wallet issue in yobit for hxx?
Yobit have asked for the source code update, stating that is the reason that the wallet is inactive.  If they receive the source code update, apparently they will be able to activate the hxx wallet on yobit so that withdrawals can be made. 
What's your take on this?

**Comment by devcon-gh** [comment]
Of course I know about the wallet issue on Yobit. The answer they gave you is just a useless standard reply. It is not something Hexx can do about. We did many requests last months via direct contact, support, twitter to get the wallet updated at Yobit. But unfortunately without luck. For now I recommend you not to use Yobit anymore. The Hexx team is on it and we won't give up.

**Comment by hexxcointakeover** [comment]
will be added later
